name: clinic
description: "تطبيق حجز المواعيد الطبية - Medics"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.2

  # Local Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.5.3

  # Network
  dio: ^5.8.0+1
  http: ^1.4.0

  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  lottie: ^2.7.0

  # Image Handling
  image_picker: ^1.1.2

  # Location
  geolocator: ^10.1.1
  google_maps_flutter: ^2.12.3

  # Validation
  form_field_validator: ^1.1.0

  # Date/Time
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSansArabic-Regular.ttf
    - assets/fonts/NotoSansArabic-Bold.ttf
    # - assets/images/
    # - assets/icons/
    # - assets/animations/
    
  
  fonts:
    - family: CustomArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700