name: clinic
description: تطبيق حجز المواعيد الطبية

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Image Handling
  image_picker: ^1.0.4
  
  # Date & Time
  intl: ^0.18.1
  
  # Animations
  lottie: ^2.7.0
  
  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  
  # Validation
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/NotoSansArabic-Regular.ttf
    - assets/fonts/NotoSansArabic-Bold.ttf
    # - assets/images/
    # - assets/icons/
    # - assets/animations/
    
  
  fonts:
    - family: CustomArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700